-- =============================================================================
-- v1.4.0 Infrastructure Migration
-- Date: 2026-03-06
-- Description: New tables for admin requests and announcements,
--              new columns on store_schedules, and audit columns on main tables.
-- =============================================================================

-- =============================================================================
-- 1. ADMIN REQUESTS TABLE
-- Flexible request system for store requests, scene requests, data errors, etc.
-- =============================================================================
CREATE TABLE IF NOT EXISTS admin_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type TEXT NOT NULL,              -- 'store_request', 'scene_request', 'data_error', 'bug_report'
    scene_id INTEGER REFERENCES scenes(scene_id),
    status TEXT NOT NULL DEFAULT 'pending',  -- pending, approved, rejected, resolved
    payload JSONB NOT NULL,                  -- flexible per request type
    discord_username TEXT NOT NULL,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolved_by TEXT,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_admin_requests_status ON admin_requests(status);
CREATE INDEX IF NOT EXISTS idx_admin_requests_type ON admin_requests(request_type);
CREATE INDEX IF NOT EXISTS idx_admin_requests_scene ON admin_requests(scene_id);

-- =============================================================================
-- 2. ANNOUNCEMENTS TABLE
-- App-wide announcements with type and optional expiry
-- =============================================================================
CREATE TABLE IF NOT EXISTS announcements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    announcement_type TEXT NOT NULL DEFAULT 'info',  -- info, donation, update, event
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ  -- NULL = no expiry
);

-- =============================================================================
-- 3. STORE SCHEDULES - NEW COLUMNS
-- week_of_month: for monthly schedules ('1st', '2nd', '3rd', '4th', 'last')
-- next_occurrence: anchor date for biweekly every-other-week patterns
-- =============================================================================
ALTER TABLE store_schedules ADD COLUMN IF NOT EXISTS week_of_month TEXT;
ALTER TABLE store_schedules ADD COLUMN IF NOT EXISTS next_occurrence DATE;

-- =============================================================================
-- 4. AUDIT COLUMNS - Add updated_by to main tables
-- These tables already have updated_at but are missing updated_by
-- =============================================================================
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE deck_archetypes ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE scenes ADD COLUMN IF NOT EXISTS updated_by TEXT;
